version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    command: gunicorn -w 4 --bind 0.0.0.0:5000 -m 007 app:app

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
